---
- name: Initialize master and worker nodes
  hosts: all
  vars:
    - docker_url_apt_key: https://download.docker.com/linux/ubuntu/gpg
    - docker_gpgpath: /etc/apt/trusted.gpg.d/docker.gpg
    - k8s_url_apt_key: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key"
    - k8s_gpgpath: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - k8s_repository: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/"
  become: true
  become_user: test
  tasks:

   - name: Disable SWAP
     shell:  |
       swapoff -a

   - name: Install dependencies
     apt:
       name: "{{ item }}"
       state: present
     with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
  
   - name: Adding Docker GPG key
     shell: curl -fsSL {{ docker_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
     args:
       creates: "{{ docker_gpgpath }}"

   - name: Adding Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
       state: present

   - name: Update apt cache again after adding docker repository
     apt:
       update_cache: yes

   - name: Installation of Containerd
     apt:
      name: containerd.io
      state: present

   - name: Setting value of SystemdCgroup
     shell: |
       containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
       sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

   - name: Restarting Service of Containerd
     service:
       name: containerd
       state: restarted
       enabled: yes

   - name: Adding Kubernetes GPG key
     shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
     args:
       creates: "{{ k8s_gpgpath }}"

   - name: Add Kubernetes apt repository
     apt_repository:
       filename: kubernetes
       repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"

   - name: Update apt cache again after adding K8 repository
     apt:
      update_cache: yes
  
   - name: Install kubelet and kubeadm
     apt:
        name: "{{ item }}"
        state: present
     loop:
       - kubeadm
       - kubelet

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

   - name: install kubectl
     apt:
        name: kubectl
        state: present
     when: "'master' in group_names"